language: python
python: 3.5
cache:
  - pip
  - apt
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libblas-dev liblapack-dev gfortran python-numpy python-scipy >/dev/null 2>&1
  - pip install flake8
install:
  - make install
script:
  - make test
notifications:
    email: false
