default:
    proso_models:
        predictive_model:
            class: proso.models.prediction.PriorCurrentPredictiveModel
    proso_feedback:
        domain: localhost
        to:
            - root@localhost
