default:
    proso_models:
        predictive_model:
            class: proso.models.prediction.PriorCurrentPredictiveModel
    proso_feedback:
        domain: localhost
        to:
            - root@localhost
    proso_tests:
        a:
            b:
                c: blah
        instantiate_ok:
            inner:
                class: proso_common.config_test.TestClass
                parameters:
                    dummy: ok
        instantiate_nok:
            class: proso_common.config_test.TestClass
    proso_flashcards:
        practice:
            common:
                set_length: 10
            intro:
                set_length: 5
                fc_queue_size_max: 5
                fc_queue_size_min: 3
                save_answer_immediately: true
                cache_context: true
