default:
    proso_models:
        predictive_model:
            class: proso.models.prediction.AlwaysLearningPredictiveModel
            parameters:
                pfae_good: 1.0
    proso_feedback:
        domain: localhost
        to:
            - root@localhost
